# Generated by Django 5.0.4 on 2024-04-27 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="order_date",
        ),
    ]
