# Generated by Django 5.0.4 on 2024-05-01 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "purchase_order",
            "0003_purchaseorder_delivered_date_purchaseorder_issues_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 8, 49, 58, 770030, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 1, 8, 49, 58, 770098, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
