# Generated by Django 5.0.4 on 2024-05-03 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_order", "0005_alter_purchaseorder_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 5, 3, 52, 5, 154480, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 3, 52, 5, 154557, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
